### ISSUE TITLE
Implied multiplication with parenthesis causes the program to panic

### ISSUE THREAD

**Issue by brooksmckinley** [Techno-coder/calculator#2]
Instructions to reproduce: type `2(2)` into the calculator

```> env RUST_BACKTRACE=full calculator -b
>> 2(2)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', /home/brooks/.cargo/git/checkouts/calculator-6d799f67a690bcf9/e292c65/src/parse.rs:25:2
stack backtrace:
   0:     0x564e2a33c394 - backtrace::backtrace::libunwind::trace::hf625d18232cbbbd4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x564e2a33c394 - backtrace::backtrace::trace_unsynchronized::h41d74150fc6ff542
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x564e2a33c394 - std::sys_common::backtrace::_print_fmt::h85d37830c667a1f9
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x564e2a33c394 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b7ac01d5feaf9b2
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x564e2a35c56c - core::fmt::write::h7fd0d904495c035f
                               at src/libcore/fmt/mod.rs:1030
   5:     0x564e2a33a337 - std::io::Write::write_fmt::h663e4bf63637c947
                               at src/libstd/io/mod.rs:1412
   6:     0x564e2a33e7e5 - std::sys_common::backtrace::_print::h4c743f7c274a5a74
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x564e2a33e7e5 - std::sys_common::backtrace::print::ha5c4f4bf03800d4d
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x564e2a33e7e5 - std::panicking::default_hook::{{closure}}::h8b842185774c09e6
                               at src/libstd/panicking.rs:196
   9:     0x564e2a33e4d6 - std::panicking::default_hook::hd8ec13ee1bc2a65a
                               at src/libstd/panicking.rs:210
  10:     0x564e2a33eee5 - std::panicking::rust_panic_with_hook::hf3b27166e5f403e7
                               at src/libstd/panicking.rs:473
  11:     0x564e2a33ea82 - std::panicking::continue_panic_fmt::hd961751be84a6f83
                               at src/libstd/panicking.rs:380
  12:     0x564e2a33e9dc - std::panicking::begin_panic_fmt::h23ef54e17e5a13fa
                               at src/libstd/panicking.rs:335
  13:     0x564e2a310bd2 - calculator::parse::parse_root::hffd6dfd8c057517c
  14:     0x564e2a31ea8b - calculator::interface::basic::evaluate::hd0e5d22875687a6a
  15:     0x564e2a31df4e - calculator::interface::basic::basic::h8916084d6e15b91a
  16:     0x564e2a31a067 - calculator::main::h276000ddf229f74c
  17:     0x564e2a30c7a7 - std::rt::lang_start::{{closure}}::h3b71ad361391ce47
  18:     0x564e2a33e913 - std::rt::lang_start_internal::{{closure}}::hf85bf15597d76295
                               at src/libstd/rt.rs:49
  19:     0x564e2a33e913 - std::panicking::try::do_call::hd308ec0604b9bc21
                               at src/libstd/panicking.rs:292
  20:     0x564e2a34146a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x564e2a33f3dd - std::panicking::try::hafc45125a5bd2b22
                               at src/libstd/panicking.rs:271
  22:     0x564e2a33f3dd - std::panic::catch_unwind::h8494678ec44c4b51
                               at src/libstd/panic.rs:394
  23:     0x564e2a33f3dd - std::rt::lang_start_internal::h7404667a595739f8
                               at src/libstd/rt.rs:48
  24:     0x564e2a31a132 - main
  25:     0x7f0a56b482e1 - __libc_start_main
  26:     0x564e2a304e1a - _start
  27:                0x0 - <unknown>
```

**Comment by Techno-coder** [comment]
Thanks for the bug report!
